config/routes.rb
Rails.application.routes.draw do
  # resources :users, only: %i[show update]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :articles, only: %i[index new create] do
    resources :comments, only: %i[new create update destroy]
  end
  namespace :my do
    resources :users, only: %i[show update destroy]
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'articles#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates :content, length: { in: 5..15 }
  validates :user_id, uniqueness: { scope: :article_id, message: 'のコメントはすでに存在します' }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[update destroy]

  def new
    if current_user && Comment.find_by(user_id: current_user.id, article_id: params[:article_id]).present?
      @comment = Comment.find_by(user_id: current_user.id, article_id: params[:article_id])
    else
      @comment = Comment.new
    end
    @comments = Comment.where(article_id: params[:article_id])

    @article = Article.find(params[:article_id])
    
  end

  def create
    # new画面でindex表示させるためのall
    @comments = Comment.where(article_id: params[:article_id])
    @article = Article.find(params[:article_id])

    # ログインしてないと投稿を止める
    return unless user_signed_in?
    # user_idとarticle_idが外部キーのため入れている
    @comment = current_user.comments.build(comment_params)
    @comment[:article_id] = params[:article_id]


    if @comment.save
      redirect_to new_article_comment_path(@comment.article_id), notice: "Comment was successfully created." 
      new_article_comment_path(@comment.article_id)
    else
      render :new
    end
    
  end

  def update
    # 他人がコメント編集できないように
    return if current_user.id != @comment.user_id
    if @comment.update(comment_params)
      redirect_to new_article_comment_path(@comment.article_id), notice: "Comment was successfully created." 
      new_article_comment_path(@comment.article_id)
    else
      @comments = Comment.where(article_id: params[:article_id])
      @article = Article.find(params[:article_id])
      render :new
    end
  end

  def destroy
    # 他人がコメント編集できないように
    return if current_user.id != @comment.user_id

    @comment.destroy

    respond_to do |format|
      format.html { redirect_to new_article_comment_path, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class = "post_comment" >
<%= form_with(model: [@article,  @comment],local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(comment.errors.count, "つエラー") %> があります。</p>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="comment_field">
    <%= form.label "コメント" %>
    <%= form.text_field :content, placeholder: "5~15文字" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-primary btn-sm" %>
  </div>
  <p>コメントは1記事に1つだけ投稿できます</p>
</div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', new_article_comment_path %>

app/views/comments/new.html.erb
<div class = "article">
  <div>
    <ul class = "article_info shadow-sm p-3 bg-white rounded border-top" >
      <h3><%= link_to @article.title, @article.link %></h3>
      <li class="comment_info text-info" >
        記事内いいね数:<%= @article.article_statistic.fav %>
        記事内コメント数:<%= @article.article_statistic.comment %>
        総合:<%= params[:ranking] %>
      </li>
      <li class = "article_source text-black-50">Yahoo!ニュース</li>
    </ul>
  </div>
</div>

<div class = "post_field" >
<h3>みんなのコメント</h3>
<% unless user_signed_in? %>
  <p>※コメント投稿にはログインが必要です</p>
<% else %>
<div class = "form_comment">
  <%= render 'form', comment: @comment %>
</div>
<% end %>
<br>
</div>


<div class = "comment_list border border-secondary rounded" >
<% @comments.reverse_each do |comment| %>
    <div class = "comment_div">
      <ul class ="each_comment shadow p-3 bg-white rounded border-top">
        <li class = "user_name">
          <%= comment.user.name %>
        </li>
        <li class = "comment_info">
          <%= image_tag "default.png", class: "default" %>
          <%= comment.content %>
          <% if user_signed_in? && current_user.id == comment.user_id %>
            <td><%#= link_to 'Edit', edit_article_comment_path(params[:article_id], comment) %></td>
            <td><%= link_to '×', article_comment_path(params[:article_id], comment), method: :delete, data: { confirm: '削除しますか?' } %>
          <% end %>
        </li>
      </ul>
    </div>
    <% end %>
</div>

<br>