config/routes.rb
Rails.application.routes.draw do
  # resources :users, only: %i[show update]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :articles, only: %i[index new create] do
    resources :comments, only: %i[new create update destroy]
  end
  namespace :my do
    resources :users, only: %i[show update destroy]
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'articles#index'
end

app/models/article.rb
class Article < ApplicationRecord
  has_one :article_statistic, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :link, presence: true

  scope :order_fav, -> { eager_load(:article_statistic).order(fav: "DESC") }
  scope :order_comment, -> { eager_load(:article_statistic).order(comment: "DESC") }
  scope :where_24hour_articles, -> { where(created_at: Time.now.yesterday..Time.now) }
  scope :where_1week_articles, -> { where(created_at: Time.now.ago(7.days)..Time.now) }

  # 並び替えアルゴリズムの部分
  def sort_article(params)
    # 時間で絞り込みをするメソッド
    articles_by_time = filter_by_time(params[:time])
    # いいね順、コメント順などでソートするメソッド
    articles = filter_by_sort_algorithm(articles_by_time, params[:sort_algorithm])
    # kaminari、array用仕様
    Kaminari.paginate_array(articles).page(params[:page]).per(100)
  end

  # 上述のアルゴリズムを詳しく設定しているコードが下記
  def filter_by_time(params_time)
    if params_time == "all_time"
      # 記事作成日時が全て
      @articles_by_time = Article.all
    elsif params_time == "1_week"
      # 記事作成日時が1週間以内のもので絞り込み
      @articles_by_time = Article.where_1week_articles
    else
      # 記事作成日時が24時間以内のもので絞り込み
      @articles_by_time = Article.where_24hour_articles
    end
  end

  def filter_by_sort_algorithm(articles_by_time, params_sort_algorithm)
    if params_sort_algorithm == 'comment'
      # 記事内コメント順で降順
      articles = articles_by_time.order_comment
    elsif params_sort_algorithm == 'fav'
      # 記事内いいね順で降順
      articles = articles_by_time.order_fav
    else
      # 記事内favとcomment数を合算して1記事ごとに反響の総数を計算している
      articles_by_time.each do |article|
        num = article.article_statistic.fav + article.article_statistic.comment
        article[:ranking] = num
      end

      # # 記事内反響の総数順で降順
      articles = articles_by_time.sort_by { |x| x[:ranking] }.reverse
    end
     # 反響の総数メソッドと同じ。最後に行う必要があるためここにあるが、
     # 「反響の総数順」メソッドの前に行う必要があるため、else文の中でも登場している
    articles.each do |article|
      num = article.article_statistic.fav + article.article_statistic.comment
      article[:ranking] = num
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index

    # 記事の並び替えアルゴリズム
    article = Article.new
    @articles = article.sort_article(params)

    # セレクトボックス
    @selectbox_time = params[:time] 
    @selectbox_sort_algorithm = params[:sort_algorithm]

  end

  # 手動スクレイピング機能（念の為残す）
  def create
    if params[:name].present?
      # スクレイピング機能
      ArticleStatistic.scraping_yahoo(params[:name].to_i)
    end
    redirect_to articles_path

  end

  # 手動スクレイピング機能（念の為）
  def new
    @article = Article.new
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% end %>
<% 5.times do |page| %>
  <%= button_to "#{page + 1}ページ目",articles_path(name: page + 1) %>
<% end %>

app/views/articles/index.html.erb
<div class = "background_image">
<div class = "top_part">
  <h3>最近、何が話題になった？</h3>
  <h5><%#= @display_the_title %></h5>
  <h5 class = "description">このサイトは、各サイトの面白い記事から読めるサイトです。</h5>

<%= form_with(url: articles_path, local: true, method: :get) do |form| %>

<table class = "sort_table">
<th>
  <div class="sort_field">
    <%= form.label "集計期間" %>
    <%= form.select :time, { '24時間ランキング': '24hours', '1週間のランキング': '1_week', '総合ランキング': 'all_time'}, { selected: @selectbox_time || '24hours'} %>
</div>
</th>
<th>
  <div class="sort_field">
    <%= form.label "並び順" %>
    <%= form.select :sort_algorithm, { 'コメント': 'comment', 'いいね': 'fav', '総合': 'total'} , { selected: @selectbox_sort_algorithm || 'total' }%>
</div>
</th>
<th>
  <%= form.submit class: "sort_btn btn btn-outline-primary btn-sm" %>
</th>
</table>
</div>
<% end %>
<div class = "article_list border border-secondary rounded" >
<% @articles.each.with_index(1) do |article, ranking_number| %>
    <div class = "article_and_comment">
      <ul class ="each_article shadow p-3 bg-white rounded border-top">
        <li class = "one_article"><%= link_to article.title, article.link, target: :_blank, rel: "noopener noreferrer"%></li>
        <li class="article_info text-info" >
          記事内いいね数:<%= article.article_statistic.fav %>
          記事内コメント数:<%= article.article_statistic.comment %>
          総合:<%= article.ranking %>
        </li>
        <li class = "one_comment" ><%= link_to 'コメント一覧', new_article_comment_path(article, ranking: article.ranking) %></li>
        <li class = "article_source text-black-50"><%= article.created_at.strftime("%y年%-m月%-d日 %-H時") %>:Yahoo!ニュース</li>
      </ul>
      <ul class = "ranking_list">
        <li class = "the_number"><%= ranking_number %>位</li>
      </ul>
    </div>
    <% end %>
</div>
<br>
<%= paginate @articles %>
</div>

app/views/articles/new.html.erb
<h1>ヤフー 主要タブ</h1>

<%= render 'form', article: @article %>