config/routes.rb
Rails.application.routes.draw do
  # resources :users, only: %i[show update]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :articles, only: %i[index new create] do
    resources :comments, only: %i[new create update destroy]
  end
  namespace :my do
    resources :users, only: %i[show update destroy]
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'articles#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :timeoutable, :trackable

  has_many :comments, dependent: :destroy
  validates :name, length: { in: 5..15 }, uniqueness: true
end

app/controllers/my/users_controller.rb
class My::UsersController < ApplicationController
  before_action :set_user, only: %i[show update destroy]

  # ゲスト用が不要になれば中身は消すコードたち
  def show
    # binding.pry
    # ゲストユーザー兼ゲスト管理者用if文
    if params[:id] == 'guest' || params[:id] == 'admin'
      if User.find_by(email: 'q@a.com')
        @user = User.find_by(email: 'q@a.com')
      else
        @user = User.create(name: 'test1', email: 'q@a.com', password: 'qqqqqq', admin: true)
        # メール認証を一時凍結したため
        # @user.confirm
      end
      # ゲストでもユーザーか管理者かで機能切り分け
      @user[:admin] = false if params[:id] == 'guest'
      @user[:admin] = true if params[:id] == 'admin'
      sign_in @user
      @current_user = @user
    end
    redirect_to rails_admin_path if params[:id] == 'admin'
  end

  def update
    if @user.update(user_params)
      redirect_to my_user_path(current_user), notice: 'ユーザー情報を更新しました'
    else
      render :show
    end
  end

  private

  def set_user
    if current_user.present?
      @user = User.find(current_user.id)
    end

  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/my/users_helper.rb
module My::UsersHelper
end

app/views/my/users/show.html.erb
<div id = "mypage">
<h2>マイページ</h2>
<%= current_user.name %>
<%= current_user.email %>
<div class="image">
  <%= image_tag "default.png", class: "default" %>
</div>
<%= form_with(model: [:my, @user],local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@user.errors.count, "つエラー") %>があります。</p>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-success" %>
  </div>

<% end %>
<div>
  <%= button_to "退会する", user_registration_path, {method: :delete, class: "btn btn-outline-success"} %>
</div>

<% if current_user.admin? %>
  <div>
    <%= link_to '管理者', rails_admin_path %>
  </div>
  <div>
    <%= link_to 'New Article', new_article_path %>
  </div>
<% end %>
</div>