config/routes.rb
Rails.application.routes.draw do
  # resources :users, only: %i[show update]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :articles, only: %i[index new create] do
    resources :comments, only: %i[new create update destroy]
  end
  namespace :my do
    resources :users, only: %i[show update destroy]
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'articles#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatInteresting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# レスポンシブ %>
    <meta name="viewport" content="width=device-width, initial-scale=0.65" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="for_bottom_footer" >
  <div id = "header", class="navbar navbar-expand-lg navbar-light bg-light bg-dark">
    <div>
      <%= link_to "記事ランキングへ", articles_path %>
      <% if user_signed_in? %>
        <%= link_to "マイページ", my_user_path(current_user) %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "新規登録", new_user_registration_path %>
        <%= link_to "ログイン", new_user_session_path %>
        <%= link_to "ゲストユーザー", my_user_path("guest") %>
        <%= link_to "ゲスト管理者", my_user_path("admin") %>
      <% end %>
    </div>
  </div>


  <% if notice %>
    <p class="alert alert-notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-error"><%= alert %></p>
  <% end %>
  <div class = "yield">
    <%= yield %>
  </div>
    
  <footer class="py-3 my-4 border-top">
    <p class="text-muted">© 2022 what_interesting</p>

  </footer>
  
  </div>
  </body>
</html>